# This is to test out custom environment variables
# Source: https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#using-variables-in-your-workflows

name: Custon Environment Varaible

on: 
  push:
    paths:
      - '.github/workflows/custom-env-variable.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  set-env:
    runs-on: ubuntu-latest

    steps:
      - run: set | sort

      - run: printenv | sort

      - name: Let echo use custom env variable
        run: echo "Hello ${{ MY_NAME }}. How are you?"
        env:
          MY_NAME: "Justin S."

      - run: set | sort

      - run: printenv | sort