# This is to test out custom environment variables
# Discovered that env variables exposed in the yaml are only available in that step as environment variables
#    after the step the environment variable is gone.
# Source: https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#using-variables-in-your-workflows

name: Custon Environment Varaible

on: 
  push:
    paths:
      - '.github/workflows/custom-env-variable.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  set-env:
    runs-on: ubuntu-latest

    steps:
      - run: set | sort

      - run: printenv | sort

      - name: Let echo use custom env variable
        run: echo "Hello ${{ env.MY_WELCOME }}. How are you?"
        env:
          MY_WELCOME: "Justin S."

      - name: Show shell variables
        run: set | sort
        env:
          MY_NAME: "Justin S."

      - name: Show env variables
        run: printenv | sort
        env:
          MY_OTHER_NAME: "Justin S."

      - run: set | sort

      - run: printenv | sort