# This is to test out custom environment variables
# Source: https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#using-variables-in-your-workflows

name: Custon Environment Varaible

on: 
  push:
    paths:
      - '.github/workflows/custom-env-variable.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  set-env:
    runs-on: ubuntu-latest

    steps:
      - run: set | sort

      - run: printenv | sort

      # Updated step to not echo a variable ${{ MY_NAME }} because it was failing
      # Error: The workflow is not valid. .github/workflows/custom-env-variable.yml (Line: 24, Col: 14): 
      #        Unrecognized named-value: 'MY_NAME'. Located at position 1 within expression: MY_NAME
      - name: Show shell variables
        run: set | sort
        env:
          MY_NAME: "Justin S."

      - name: Show env variables
        run: printenv | sort
        env:
          MY_OTHER_NAME: "Justin S."

      - run: set | sort

      - run: printenv | sort