# This is to test out the JavaScript action I built.
# Source Code of Custom Action: https://github.com/jswanso/hello-world-javascript-action
# Documentation Used in Building Custom Action: https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action

name: Hello World Action

on: 
  push:
    paths:
      - '.github/workflows/hello-world-action.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hello-world-action:
    runs-on: ubuntu-latest

    name: A job to say hello

    steps:
      - name: Hello world action step
        id: hello
        uses: jswanso/hello-world-javascript-action@v1.2
        with:
          who-to-greet: 'Justin'
      
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"