# This is to test out the action I built.

name: Hello World Action

on: 
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hello-world-action:
    runs-on: ubuntu-latest

    name: A job to say hello

    steps:
      - name: Hello world action step
        id: hello
        uses: jswanso/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'Justin'
      
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"